---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: UpdateConfigs
    inherits: 
    description: 
  fields:
  - rel1:
      value: "/MyEmailDomain/Code/ProcessEmailConfig/UpdateEmailConfigs"
